### ISSUE TITLE
[bug] Renovate upgrades to v1.3.0: no assets to download

### ISSUE THREAD

**Issue by konstruktoid** [slsa-framework/slsa-github-generator#1250] opened 2022-11-21 12:06 UTC
**Describe the bug**

```console
Run ./__BUILDER_CHECKOUT_DIR__/.github/actions/generate-builder/generate-builder.sh
  ./__BUILDER_CHECKOUT_DIR__/.github/actions/generate-builder/generate-builder.sh
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    BUILDER_BINARY: slsa-generator-generic-linux-amd64
    BUILDER_DIR: ./__BUILDER_CHECKOUT_DIR__/internal/builders/generic
    BUILDER_REPOSITORY: slsa-framework/slsa-github-generator
    BUILDER_RELEASE_BINARY: slsa-generator-generic-linux-amd64
    VERIFIER_REPOSITORY: slsa-framework/slsa-verifier
    VERIFIER_RELEASE_BINARY: slsa-verifier-linux-amd64
    VERIFIER_RELEASE_BINARY_SHA256: b1d6c9bbce6274e253f0be33158cacd7fb894c5ebd643f14a911bfe55574f4c0
    VERIFIER_RELEASE: v1.3.2
    COMPILE_BUILDER: false
    BUILDER_REF: refs/tags/v1.3.0
    GH_TOKEN: ***
Fetching the builder with ref: refs/tags/v1.3.0
Builder version: v1.3.0
BUILDER_REPOSITORY: slsa-framework/slsa-github-generator
no assets to download
Error: Process completed with exit code 10.
```

https://github.com/konstruktoid/ansible-role-hardening/actions/runs/3512750596/jobs/5884806849#step:2:557
https://github.com/konstruktoid/ansible-role-docker-rootless/actions/runs/3514186184/jobs/5887905261#step:2:557
https://github.com/konstruktoid/hardening/actions/runs/3514179542/jobs/5887890423#step:2:557

**Additional context**

Renovate upgrades slsa-framework/slsa-github-generator action to v1.3.0

https://github.com/konstruktoid/ansible-role-hardening/pull/208
https://github.com/konstruktoid/ansible-role-docker-rootless/pull/90
https://github.com/konstruktoid/hardening/pull/199

**Comment by laurentsimon** [comment] 2022-11-21 18:08
Thanks. The v1.3.0 is marked as "pre-release", until we run all the pre-release tests. can renovatebot be configured to not send PRs in this case? I know that dependabot does not, for example.

**Comment by laurentsimon** [comment] 2022-11-21 18:11
@rarkins Could you point us in the right direction?

**Comment by rarkins** [comment] 2022-11-21 19:27
In future I recommend against using stable semver versions for pre-releases, as you may confuse humans and bots alike. 

Renovate is upgrading _tags_ here, and tags don't have prerelease designations - only _releases_ do. If you are using either assets or release metadata (prerelease) then we'd need to switch to using GitHub releases only and no longer tags (even though GitHub Actions works off tags, as far as I'm aware). This means any tag you intend to be stable but which is missing a release would be ignored, as well as any release you designate as unstable.

**Comment by ianlewis** [comment] 2022-11-21 23:46
@rarkins Thanks for the suggestions. Unfortunately we need to do pre-release tests which require exercising our [verifier](https://github.com/slsa-framework/slsa-verifier) which requires us to use semver tags. We uncheck the pre-release checkbox after pre-release tests are done. That's really the only way for us to properly test the releases.

As a GHA CI/CD tool, we need to test after the tag is created and the reusable workflow is tied to this repository. So running tests in another repository risks us breaking production releases because of differences in repo settings etc. and we can't create separate non-semver tags for pre-releases because our SLSA verifier requires semver tags.

It feels like we're a strange edge case for this kind of thing...

**Comment by rarkins** [comment] 2022-11-22 12:14
It seems like Renovate should switch to looking up releases instead of tags, in which case this pre-release flag is known and such PRs shouldn't be raised. I created a bug on Renovate and after confirmation from my co-maintainers we'll try to prioritize this change getting into production quickly: https://github.com/renovatebot/renovate/issues/19033

**Comment by HonkingGoose** [comment] 2022-11-23 10:54
Heads-up: we closed the Renovate issue. It looks like the problem is _not_ with Renovate: [^quote]

> GitHub actions uses git refs, not GitHub releases. From [the documentation](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_iduses):
> 
> > The location and version of a reusable workflow file to run as a job. Use one of the following syntaxes:
> > 
> > * `{owner}/{repo}/.github/workflows/{filename}@{ref}` for reusable workflows in public repositories.
> > * `./.github/workflows/{filename}` for reusable workflows in the same repository.
> > 
> > **`{ref}` can be a SHA, a release tag, or a branch name.**
> 
> GitHub releases are unrelated to GitHub Actions. GitHub releases are required to publish an action to the marketplace, but the marketplace is only for discoverability.
> 
> The issue is the `slsa-github-generator` expects there to be an equivalent GitHub release:
> 
> https://github.com/slsa-framework/slsa-github-generator/blob/800ff15cbd48bfceacd65fb8e8c5f129071b841d/.github/actions/generate-builder/builder-fetch.sh#L65

[^quote]: https://github.com/renovatebot/renovate/issues/19033#issuecomment-1324159757

**Comment by rarkins** [comment] 2022-11-23 13:51
To resolve this problem for SLSA we'll instead move this forward: https://github.com/renovatebot/renovate/issues/19032

What this means is that we'll supplement github tags with github releases metadata whenever they correlate, which means we'll learn that 3.0.0 in this case is pre-release and therefore suppress it by default

**Comment by laurentsimon** [comment] 2022-11-23 17:30
Thank you for the quick follow-up. Do you know how hard it is to implement and the timeline you envisage?

**Comment by rarkins** [comment] 2022-11-24 07:41
I estimate 1-2 weeks

**Comment by konstruktoid** [comment] 2022-12-05 14:32
This works as expected after updating, using renovate, slsa-framework/slsa-github-generator action to v1.4.0

**Comment by laurentsimon** [comment] 2022-12-06 00:12
Thanks @konstruktoid 
We have also changed how we do the release, and we use `vX.Y.Z-rc` to further mitigate this problem. I'll keep this issue opened until @rarkins has landed the new feature from renovate.

**Comment by ianlewis** [comment] 2023-04-04 01:45
I think this should be solved now that https://github.com/renovatebot/renovate/issues/19032 was finished and we now do RC releases to mitigate this issue.

**Closed by ianlewis** 2023-04-04 01:45 UTC
Labels: type:bug, area:generic, area:tooling
