### ISSUE TITLE
[e2e]: generic schedule main multi-subjects slsa3 

### ISSUE THREAD

**Issue by ianlewis** [slsa-framework/slsa-github-generator#600] opened 2022-07-21 04:51 UTC
Repo: https://github.com/slsa-framework/example-package/tree/main
Run: https://github.com/slsa-framework/example-package/actions/runs/2709376655
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.generic.schedule.main.multi-subjects.slsa3.yml
Workflow runs: https://github.com/slsa-framework/example-package/actions/workflows/e2e.generic.schedule.main.multi-subjects.slsa3.yml
Trigger: schedule
Branch: main
Date: Thu Jul 21 04:51:40 UTC 2022

**Comment by asraa** [comment] 2022-07-21 14:49
dupe of https://github.com/slsa-framework/slsa-github-generator/issues/601

**Closed by asraa** 2022-07-21 14:49 UTC
Labels: type:bug, workflow:generic, e2e
