### ISSUE TITLE
[bug] Generic workflow fails on repositories that don't use Go

### ISSUE THREAD

**Issue by behnazh-w** [slsa-framework/slsa-github-generator#376] opened 2022-06-21 22:57 UTC
**Describe the bug**
If I understand correctly the generic workflow is meant to generate provenance for any language as long as the encoded hash digest of the built artifact is provided as input. However, when I try it on a repository that doesn't use Go (e.g., uses Python) it fails because it tries to download the Go module dependencies.

https://github.com/slsa-framework/slsa-github-generator/blob/668a33920550fa6983e6c850f69da89d28b057eb/.github/workflows/generator_generic_slsa3.yml#L71-L88

Why does the workflow need to download Go modules of the target repository? Please let me know if I'm missing something.

**To Reproduce**
Run the generic workflow on a repo that doen't use Go.

**Screenshots**
![image](https://user-images.githubusercontent.com/27933054/174910006-1da781ac-7738-455d-a2fe-d6e364045d09.png)

**Comment by laurentsimon** [comment] 2022-06-22 12:44
The code you linked is to build the builder, not the project.
Here's an e2e test that succeeds https://github.com/slsa-framework/example-package/blob/main/.github/workflows/e2e.generic-bazel.push.main.default.slsa3.yml#L27-L66

Maybe you're using a trigger we have not tested yet. Can you link to a workflow you use to call the generic workflow?

**Comment by behnazh-w** [comment] 2022-06-22 22:59
[Here](https://github.com/behnazh-w/slsa-examples/blob/main/.github/workflows/pull-request.yaml) is the example workflow that fails.

> The code you linked is to build the builder, not the project.

Note that my example repo is resolved [here](https://github.com/behnazh-w/slsa-examples/runs/7012632489?check_suite_focus=true#step:2:4) at the checkout step.

**Comment by ianlewis** [comment] 2022-06-23 01:45
Hi again @behnazh-w! Thanks for the bug report and for the links. Those were super helpful for figuring out what happened.

This is caused by the fact that we don't support the `pull_request` trigger for Github Actions. See the [docs](https://github.com/slsa-framework/slsa-github-generator/tree/main/internal/builders/generic#supported-triggers) for the generic workflow. Supporting it is kind of difficult for permissions related issues. Relevant GitHub issues are #358 and #131.

What happened in this case is that our [detect-workflow](https://github.com/slsa-framework/slsa-github-generator/tree/main/.github/actions/detect-workflow) action returned empty strings for the repository and ref which then got fed into the `checkout` action and it checked out your repository (since the repo on the github context is the default).
@laurentsimon We should probably do something to make this a bit more intuitive. Maybe error out early on `pull_request` triggers (though we still need to support e2e tests).

@behnazh-w Note also that you want to include the asset name in the digest you send to the workflow so you don't really want to use awk [here](https://github.com/behnazh-w/slsa-examples/blob/main/.github/workflows/build.yaml#L45). I believe the workflow will error out if the name isn't present.

**Comment by behnazh-w** [comment] 2022-06-23 06:27
Thanks. I had missed it in the docs that `pull_request` is not supported. It works fine on the `push` trigger :+1:

**Comment by ianlewis** [comment] 2022-06-23 07:00
> Thanks. I had missed it in the docs that `pull_request` is not supported. It works fine on the `push` trigger 👍

Great to hear. I'll go ahead and close this but feel free to reopen or create a new issue if you find something else!

**Closed as completed by ianlewis** 2022-06-23 07:00 UTC
Labels: type:bug, area:generic
